### PR TITLE
[qml-plugin-email] Use systemd to start messageserver if down. Contributes JB#30477

### PR DESCRIPTION
**Pull request by VDVsx**
If process is not started via systemd unit later another process might try to
start this unit and the server will fail since only one can run at time.

### CODE REVIEW

**Comment by VDVsx** [comment]
@matthewvogt Please have a look. Thanks

**Comment by matthewvogt** [comment]
Do we see an error reported if systemctl can't start the server?

**Comment by VDVsx** [comment]
In the logs yes, if the unit just does not exist (e.g messageserver56) no, but ipc connection will also stay down and no action progresses.

**Comment by matthewvogt** [comment]
LGTM

**Comment by saukko** [comment]
You really shouldn't use systemctl call but either dbus or C api. Can't currently give a link because of connectivity that I have but you should find that with google in your locations ;)

**Pull request merged**
